lib/tsconfig.json
=> Fixed crash on boot due to not specifying types for vuetify

lib/src/App.vue, lib/src/components/Header.vue
Fixed #4
- Added a nice looking header.
=> Added header

lib/src/components/Timeline.vue
Fixed #8
- Added timeline component
- It takes a comments prop containing sorted comment objects, with a body and author key
=> Added timeline component

lib/package-lock.json, lib/package.json, lib/src/store/index.ts
Fixed #24
- Added persistant-storage to Vuex
- Added example comment state to store
=> Added persistant storage to Vuex with example

.github/workflows/tests.yml
=> Configured ESLinter action

lib/src/views/Home.vue
=> Added a welcome page

lib/src/App.vue, lib/src/components/Header.vue
Fixed #28
- No content should now be hidden behind the header
=> Fixed content hidden behind header

lib/package-lock.json, lib/src/components/Header.vue, lib/src/components/Timeline.vue, lib/src/store/index.ts, lib/src/views/Home.vue
=> fixed liniting issues

lib/src/App.vue
Fixed #40
chnaged the background color to be darker
=> fixed background color

lib/src/store/index.ts, lib/src/store/modules/journals.ts
Fixed #38
- Added Journals as a Vuex module
=> Added vuex Journal module

lib/src/components/CommentInput.vue, lib/src/views/StudentJournal.vue
=> seperated the comment input into it's own componenet

lib/src/router/index.ts, lib/src/views/Login.vue, lib/src/views/StudentJournal.vue
Fixed #3
made a view template for the login page, also made a few changes in the studentJournal code
=> Login page fixed template

lib/package-lock.json, lib/src/components/CommentInput.vue, lib/src/components/Header.vue, lib/src/router/index.ts, lib/src/views/Login.vue, lib/src/views/StudentJournal.vue
- Added router links in header
- Linting
-
=> Update router links in header

lib/src/components/CommentInput.vue, lib/src/components/UserOverview.vue, lib/src/components/UserOverviewBadge.vue, lib/src/router/index.ts, lib/src/store/index.ts, lib/src/store/modules/users.ts, lib/src/views/Login.vue, lib/src/views/StudentJournal.vue
Fixed #33
- Added base store module for users
- Added basic journal overview page
- Make this a lot more general.
=> Initial go at journal overview

lib/src/components/Header.vue, lib/src/store/index.ts, lib/src/store/modules/auth.ts, lib/src/store/modules/d.ts, lib/src/store/modules/journals.ts, lib/src/store/modules/users.ts, lib/src/views/Login.vue
Fixed #6
Fixed #11 
Fixed #12
- Added auth module to store
- Added login functionality
- Added logout functionality
- Implemented functionality in to the header 
- Implemented basic functionality to the login component**
** Input the user ID into the email input to login otherwhise it defaults to user 1 
=> Implemented login/logout features

lib/src/components/NewUserForm.vue, lib/src/components/UserOverview.vue
Fixed #7
Added Admin page and fixed a lot of issues
=> Implement fixed admin page 

lib/src/components/JournalBox.vue, lib/src/components/Timeline.vue, lib/src/store/modules/journals.ts, lib/src/views/StudentJournal.vue
Fixed a "bug" implemented in #70
- Fixed a "bug" where it didn't update the view with the correct data for a given day when navigating using the day selector.
=> Allow for changing day using the 'header' coponent

lib/src/components/JournalBox.vue, lib/src/store/modules/d.ts, lib/src/store/modules/journals.ts, lib/src/views/StudentJournal.vue
Fixed #62
- Automatically save input data in journal to store
=> Saves logbook input to the store

lib/src/components/JournalOverview.vue
Fixed #77
- Added dynamic linking in table head
=> Dynamically generate table head

lib/src/components/JournalOverview.vue, lib/src/components/Timeline.vue
Fixed #76
- Added a dynamic comment counter to the journal overview component
=> Dynamic comment counter

.github/workflows/cc.yml, docs/README.md, lib/package.json, lib/src/components/Timeline.vue
Related to #1
Fixed #13
- Setup code coverage with CodeClimate
- Setup github action for automatic reporting
=> Setup code coverage with CodeClimate

lib/src/router/index.ts, lib/src/views/Teacher.vue
Fixed #54
Fixed #52
- Dynamically loading data from the store in the `/teacher` view
- Added the ability to change user within the `/teacher` view
- This could probably be splitted up into multiple components
=> Dynamically inserting and reacting to Vuex data

lib/src/components/CommentInput.vue, lib/src/store/modules/d.ts, lib/src/store/modules/journals.ts, lib/src/views/StudentJournal.vue, lib/src/views/Teacher.vue
Fixed #48
- Rewamped comment functionality in store
- Added store interaction to the comment box component
- Passes in additional props to the comment box in all required views
=> The creation of comments

lib/src/router/index.ts, lib/src/store/modules/auth.ts
Fixed #83
- Added route securing
- Added isAdmin in auth store
- Added isStudent in auth store
=> Securing routes

lib/src/components/JournalCard.vue, lib/src/views/Teacher.vue
Fixed #79
Made it possible to view all journals of a day at once
=> All at once

lib/src/components/JournalBox.vue, lib/src/components/JournalCard.vue, lib/src/views/Teacher.vue
Fixed #94
- Correctly fills data in teacher all view
- Disabled input fields for teachers in journal views
=> Fixed wrong data insertion in student view

lib/tests/unit/App.spec.ts
=> added test to check if header renders in app

lib/tests/unit/Timeline.spec.ts
=> henrik simple jest test

docs/CodeStyling.md, docs/_navbar.md, lib/tests/unit/App.spec.ts, lib/tests/unit/Timeline.spec.ts
=> code styling documentation

lib/src/components/Header.vue
Fixed #100
Fixed the header buttons
=> Fixed the header buttons
